### ISSUE TITLE
hide debug output by default

### ISSUE THREAD

**Issue by waspinator** [adafruit/Adafruit_CircuitPython_MLX90640#11]
Would it be a good idea to hide print statements by default? I can make PR if that's the case. 

https://github.com/adafruit/Adafruit_CircuitPython_MLX90640/blob/032427e47cdc8906b83861ec778ebade318f02ce/adafruit_mlx90640.py#L769

**Comment by tannewt** [comment]
@waspinator Have you found a case that hits it? It looks like it'll be only in rare cases.

**Comment by waspinator** [comment]
it prints every time for me. It just says `Found 0 broken pixels, 0 outliers`. I have a script that outputs the data to standard out, and while not a big deal, I have to ignore that debug line.

**Comment by tannewt** [comment]
@waspinator Ah right. Please make a PR to comment it out. Thanks!

**Comment by kattni** [comment]
This has been resolved.
