### ISSUE TITLE
Not working with FT232H

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_MLX90640#15]
Ref this thread:
https://forums.adafruit.com/viewtopic.php?f=19&t=164383

I think maybe we knew this? But not sure if we've documented why anywhere. Or if it's something that can be fixed. Opening here first, but may be more of a Blinka issue.

**Comment by ladyada** [comment]
yeah it def works with the MCP which has a better I2C interface
https://learn.adafruit.com/jupyter-on-any-computer-with-circuitpython-libraries-and-mcp2221/thermal-camera
the FT232H doesnt work but i cant remember why, i think it cant read I2C fast enough?

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_Blinka/issues/208

**Comment by caternuson** [comment]
Thanks! Yeah. I knew we knew. :)

FWIW, traces:

**MCP221 getFrame:** (~40ms)
![mcp2221_getframe](https://user-images.githubusercontent.com/8755041/79596567-a4b48d80-8095-11ea-8d46-82e5ca814292.jpg)
**FT232H getFrame:** (~800ms)
![ft232h_getframe](https://user-images.githubusercontent.com/8755041/79596582-aa11d800-8095-11ea-9127-2dc92ffebcab.jpg)

**Comment by ladyada** [comment]
yeah mcp is happy to do 'big ass chunks' of i2c data...but ft232h is not, so you get 1 byte per 1ms usb frame :( do you want to look at if multibyte is possible?

**Comment by walchko** [comment]
FYI ... it works for me on the ft232h board using macOS. I am using the Sparkfun version with your driver.

![IMG_9955 2](https://user-images.githubusercontent.com/918960/85951406-12e8bc80-b931-11ea-93c3-b3235d24d718.png)

**Comment by caternuson** [comment]
So, coming back to this and taking a look and ...uh....it just works now? At least if you slow I2C clock down to 100kHz.
```python
i2c = busio.I2C(board.SCL, board.SDA, frequency=100000)
```
and then:
```
$ export BLINKA_FT232H=1
$ python3 mlx90640_simpletest.py 
MLX addr detected on I2C
['0x728', '0x5fa7', '0x186']
Read 2 frames in 1.38 s
xx+xxxxxxx+xxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxx%xxxxxxxxxxxxxx
xxxxxxxxxxxxxxxx%x%x%xxxxxxxxxxx
xxxx+xxxxxx%xxx%x%x%x%x%xxxxxxxx
xxxxxxxxx+xxx+%x%x%x%x%xxxxxxxxx
xxxxxxxxxxx%x%x%x%x%x%x%xxxxxxxx
xxxxx+xxxx%x%x%x%x%x%x%xxxxxxxxx
xxxxxxxxxxx%x%x%x%x%x%xxxxxxxxxx
xxxxxxxxxx%x%x%x%x%x%xxxxxxxxxxx
xxxxxxxxx%x%x%x%x%x%x%x%xxxxxxxx
xxxxxxxx%x%x%x%x%x%x%x%xxxxxxxxx
x+xxxxx%x%x%x%x%x%x%x%x%xxxxxxxx
xxxxxx%x%x%x%x%x%x%x%x%xxxxxxxxx
xxxxxxx%x%x%x%x%x%x%x%x%xxxxxxxx
xxxxxx%x%x%x%x%x%x%x%xxxxxxxxxxx
xxxxxxx%x%x%x%x%x%x%x%x%x%x%xxxx
xxxx%x%x%x%x%x%x%%%%%xxxxx%xxxxx
xxx%x%x%x%x%x%%%%#X%#%x%x%xxx%x%
%x%x%x%x%x%x%x%x%%#X##%xxxxxxx%x
x%x%x%x%x%x%x%%%%#X#X#%%xxx%x%x%
%x%x%%%%%x%xx%%%#%#X#X#%%x%xxxxx
```

**Comment by caternuson** [comment]
Works at 400kHz also. Still not fully working at 800kHz. 
```python
$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board
>>> import busio
>>> i2c = busio.I2C(board.SCL, board.SDA, frequency=800000)
>>> import adafruit_mlx90640
>>> mlx = adafruit_mlx90640.MLX90640(i2c)
>>> mlx.serial_number
[11048, 1959, 24454]
>>> frame = [0]*768
>>> mlx.getFrame(frame)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/methuzla/blinka/lib/python3.8/site-packages/adafruit_mlx90640.py", line 131, in getFrame
    self._CalculateTo(mlx90640Frame, emissivity, tr, framebuf)
  File "/home/methuzla/blinka/lib/python3.8/site-packages/adafruit_mlx90640.py", line 303, in _CalculateTo
    Sx = math.sqrt(math.sqrt(Sx)) * self.ksTo[1]
ValueError: math domain error
>>>
```
but with a different error.

MLX90640 claims to be OK up to 1MHz:
![image](https://user-images.githubusercontent.com/8755041/110713034-14ec6600-81b6-11eb-827e-d9e754d569c6.png)

I'm going to close this for now since it can work with FT232H. Can reopen, or start a new issue, if more investigation is needed.

**Comment by ladyada** [comment]
🤷 yay! 🥳
