### ISSUE TITLE
Why do i get value > 300 with function "getFrame" ?

### ISSUE THREAD

**Issue by jerOnGHub** [adafruit/Adafruit_CircuitPython_MLX90640#16]
Hi, I recently use your library to get data from the MLX90640.
When i get data with the function "getFrame" which say in description "...and calculate the temperature in C for each of 32x24 pixels...".
datasheet of MLX90640 say it can measure temperature from -40 to 300°C, so do you have any clue why i get lots of value > 300 ? (i am measuring a 3D printing process, max temperature should be around 200°)

Thanks in advance for your reply,
Jerevi.

**Comment by ladyada** [comment]
where did you purchase the MLX90640?

**Comment by jerOnGHub** [comment]
I bought the sensor on mouser ;

link here : https://www.mouser.fr/ProductDetail/Adafruit/4469?qs=%2Fha2pyFadugtrIHlfDWZQcOKtqdMsXEhVYB5qKyQ3DlMsvQoyRAr2Yw57n4Ed2236DisuIXAv8%252BquFKWT%2FIg%252BV0Nib%2FGYO4xmaVgOc%2FCqmfr8fS2S0duitM%252Bn%252BQtdBP04lsskYt1kpf1CVaPwGqrsvSFOtNKGdMT

**Comment by ladyada** [comment]
ok for tech support please post in forums - this is for code tracking only.
thanx!
