### ISSUE TITLE
typo in comment?

### ISSUE THREAD

**Issue by ramgarden** [adafruit/Adafruit_CircuitPython_MLX90640#2]
https://github.com/adafruit/Adafruit_CircuitPython_MLX90640/blob/013eac4fcff27d6332cf1ce0a6df7526a0e4f5df/examples/mlx90640_camtest.py#L17

should be:  Must _set_ I2C freq...

# MUST et I2C freq to 1MHz in /boot/config.txt

**Comment by ladyada** [comment]
OK please submit a PR with typo fix :)

**Comment by caternuson** [comment]
Fixed by #8
