### ISSUE TITLE
Add example to save image to file?

### ISSUE THREAD

**Issue by ramgarden** [adafruit/Adafruit_CircuitPython_MLX90640#3]
https://github.com/adafruit/Adafruit_CircuitPython_MLX90640/blob/013eac4fcff27d6332cf1ce0a6df7526a0e4f5df/examples/mlx90640_camtest.py#L113

Should we add a few lines in here to show how to use the PIL Image.save() function to save the pictures to a file?
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save

**Comment by ladyada** [comment]
adding a comment or new example would be fine - a PR would be welcome!

**Comment by caternuson** [comment]
@ramgarden Would a separate example be OK? That example continuously reads and updates a pygame display. Adding a PIL save in the loop would create lots of files, or just keep orverwriting the existing one. It would also slow down the pygame display update.

**Comment by kattni** [comment]
This is resolved.
