### ISSUE TITLE
Should use simpleio.map_range in mlx90640_pygamer example.

### ISSUE THREAD

**Issue by dglaude** [adafruit/Adafruit_CircuitPython_MLX90640#6]
Talking with @CedarGroveStudios author of https://github.com/CedarGroveStudios/Thermal_Camera, I figured out that for mapping from temperature to colour palette index, I could use simpleio.map_range rather than a custom made function like I did:
https://github.com/adafruit/Adafruit_CircuitPython_MLX90640/blob/874651ca04b0aea92d54c984203a360784e3acd6/examples/mlx90640_pygamer.py#L79

This is not blocking, maybe just to put on my todo list, but anybody is welcomed to fix this before me.

The only additional feature that could make sense would be C° to F° conversion of the min and the max, that could be added. Anything else would be advance feature and not good for an example.

Any other code review is welcome.

**Comment by dglaude** [comment]
This issue is fixed with Pull request #7.

**Comment by caternuson** [comment]
OK, wanna close issue?

[EDIT] oh, wait, i see, it's not merged yet. nvm.

**Comment by caternuson** [comment]
Now it's merged :)
Thanks for the update!
